apiVersion: v1
kind: Service
metadata:
  name: headless-service
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: mongodb
spec:
  clusterIP: None # This flag makes the service headless
  selector:
    project: roboshop
    env: dev
    component: mongodb   # Routes to pods with this label
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: mongodb
spec:
  selector:
    matchLabels:
      project: roboshop
      env: dev
      component: mongodb # has to match .spec.template.metadata.labels
  serviceName: "mongodb-headless"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        component: mongodb # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mongodb
        image: jujjurisowjanya/mongodb:1.4.0
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
 name: mongodb
 namespace: roboshop
 labels:
   project: roboshop
   env: dev
   component: mongodb
spec:
  selector:
    project: roboshop
    env: dev
    component: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
