apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
  # property-like keys; each key maps to a simple value
    project: roboshop
    env: dev
    component: catalogue
data: 
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: catalogue
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      env: dev
      component: catalogue
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        component: catalogue
    spec:
      containers:
      - name: catalogue
        image: jujjurisowjanya/catalogue:1.4.0
        imagePullPolicy: Always
        resources:
          requests:
           memory: "128Mi"
           cpu: "100m"
          limits:
           memory: "128Mi"
           cpu: "100m"
        readinessProbe:
          tcpSocket:
            port: 8080
          periodSeconds: 10
          failureThreshold: 2
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
           path: /health
           port: 8080
          failureThreshold: 2
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: catalogue
---
apiVersion: v1
kind: Service
metadata:
 name: catalogue
 namespace: roboshop
 labels:
   project: roboshop
   env: dev
   component: catalogue
spec:
  selector:
    project: roboshop
    env: dev
    component: catalogue
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catalogue
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogue
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
